/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yourname.projectinfo;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class ProjectInfoPlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {
        // Регистрируем задачу "projectInfo" типа ProjectInfoTask
        project.getTasks().register("projectInfo", ProjectInfoTask.class, task -> {
            task.setGroup("reporting");  // Группа для удобства (появится в `gradle tasks`)
            task.setDescription("Prints project statistics");
        });
    }
}
